---
title: "DW Nominate Scores for Sam Johnson (TX-03)"
author: "Pegah Moradi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(gdata)
library(readr)
library(haven)

tx3dwn <- read_csv("dwNominate.csv")
housedwn = read_dta("housedwn.dta")
```

```{r include=FALSE}
recentDemCongress = housedwn %>% filter(cong > 101 & party == 100)
recentGOPCongress = housedwn %>% filter(cong > 101 & party == 200)
recentGOPCongress <- recentGOPCongress %>% group_by(cong) %>% summarise(avg = mean(dwnom1), med = median(dwnom1))
recentDemCongress <- recentDemCongress %>% group_by(cong) %>% summarise(avg = mean(dwnom1), med = median(dwnom1))
recentWholeChamber <- housedwn %>% filter(cong > 101)
recentWholeChamber <- recentWholeChamber %>% group_by(cong) %>% summarise(avg = mean(dwnom1), med = median(dwnom1))
```


```{r echo=FALSE}
ggplot(tx3dwn, aes(x = cong, y = First.Dimension.Coordinate, color = "black")) + geom_point() +
  geom_point(data=recentGOPCongress, aes(x = cong, y = med,color = 'red')) + labs(title = "Sam Johnson (TX-03) DWNominate Scores", x = "Congress", y = "DWNominate Score")+
  scale_color_manual(name = NULL, values =c("black"="black","red"="red"), labels = c('Sam Johnson (TX-03)','House Republican Median'))
```

```{r echo=FALSE}
ggplot(tx3dwn, aes(x = cong, y = First.Dimension.Coordinate, color = "black")) + geom_point() +
  geom_point(data=recentGOPCongress, aes(x = cong, y = med,color = 'red')) +
  geom_point(data=recentDemCongress, aes(x = cong, y = med, color = 'blue')) +
  geom_point(data=recentWholeChamber, aes(x = cong, y = med, color = 'purple'))+
  labs(title = "Sam Johnson (TX-03) DWNominate Scores", x = "Congress", y = "DWNominate Score") +
  scale_color_manual(name = NULL, values =c("black"="black","blue"="blue",  "purple"="purple","red"="red"), labels = c('Sam Johnson (TX-03)', "House Democrat Median", "House Median",'House Republican Median'))
```
