---
title: "Demographics for TX-03 Congressional District"
author: Pegah Moradi
output: html_notebook
---
```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(gdata)
library(readr)
```
## Sex
```{r}
tx3_sexage <- read_csv("tx3_sexage.csv")
ggplot(tx3_sexage[2:3,], aes(x = Title, y = Proportion, fill = Title)) + geom_col() + labs(title = "Gender in TX-03", x = "Gender", y = "Proportion") + theme(legend.position="none")
```
## Age
```{r}
tx3_sexage <- read_csv("tx3_sexage.csv")
#Turn your 'treatment' column into a character vector
tx3_sexage$Title <- as.character(tx3_sexage$Title)
#Then turn it back into an ordered factor
tx3_sexage$Title <- factor(tx3_sexage$Title, levels=unique(tx3_sexage$Title))
ggplot(tx3_sexage[4:16, ], aes(x = Title, y = Proportion, fill = Title)) + geom_col() + labs(title = "Age in TX-03", x = "Age Group", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 10,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))

ggplot(tx3_sexage[20:22, ], aes(x = Title, y = Proportion, fill = Title)) + geom_col() + labs(title = "Age in TX-03", x = "Age Group", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 10,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))

```
## Race
```{r}
tx3_race <- read_csv("tx3_race.csv")
ggplot(tx3_race[2:8,], aes(x = Title, y = Proportion, fill = Title)) + geom_col() + labs(title = "Race in TX-03", x = "Race", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))
```

## Income
```{r}
tx3_income <- read_csv("tx3_income.csv")
#Turn your 'treatment' column into a character vector
tx3_income$Title <- as.character(tx3_income$Title)
#Then turn it back into an ordered factor
tx3_income$Title <- factor(tx3_income$Title, levels=unique(tx3_income$Title))
ggplot(tx3_income[2:11,], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Incomes in TX-03", x = "Income Group", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))
```

## Insurance Coverage
```{r}
tx3_insured <- read_csv("tx3_insured.csv")
#Turn your 'treatment' column into a character vector
tx3_insured$Title <- as.character(tx3_insured$Title)
#Then turn it back into an ordered factor
tx3_insured$Title <- factor(tx3_insured$Title, levels=unique(tx3_insured$Title))
ggplot(tx3_insured[c(2,5),], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Insurance Coverage in TX-03", x = "Insurance Coverage", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))

tx3_insured$Title <- factor(tx3_insured$Title, levels=unique(tx3_insured$Title))
ggplot(tx3_insured[3:5,], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Insurance Coverage Type in TX-03", x = "Insurance Coverage", y = "Proportion") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))
```

## Occupation and Employment
```{r}
tx3_occupation <- read_csv("tx3_occupation.csv")

ggplot(tx3_occupation[2:6,], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Occupational Distribution in TX-03", x = "Occupation", y = "Proportion of Employed Civilians Aged 16+") + theme(legend.position="none") + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

tx3_industry <- read_csv("tx3_industry.csv")

ggplot(tx3_industry[2:14,], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Industry Employment Distribution in TX-03", x = "Industry", y = "Proportion of Employed Civilians Aged 16+") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1)) + scale_x_discrete(labels = function(x) str_wrap(x, width = 30))
```


## Education
```{r}
tx3_education <- read_csv("tx3_education.csv")
#Turn your 'treatment' column into a character vector
tx3_education$Title <- as.character(tx3_education$Title)
#Then turn it back into an ordered factor
tx3_education$Title <- factor(tx3_education$Title, levels=unique(tx3_education$Title))
ggplot(tx3_education[2:8,], aes(x = Title, y = Relevant.Proportion, fill = Title)) + geom_col() + labs(title = "Education in TX-03", x = "Highest Level of Education", y = "Proportion of Adults Aged 25+") + theme(legend.position="none", axis.text.x =
               element_text(size  = 7,
                            angle = 45,
                            hjust = 1,
                            vjust = 1))
```


